version: '3'

services:
  web:
    build:
      context: ./
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - db
  
  db:
    image: mysql:8.0  # Use MySQL 8 for Apple Silicon support
    platform: linux/amd64  # Ensures compatibility on M1/M2 Macs
    environment:
      - MYSQL_ROOT_PASSWORD=mywebpassword
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
